import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider } from "@/context/store-context";
import ProviderWrapper from "@/redux/store-wrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning={true}>
                <ProviderWrapper>
                    <StoreProvider>{children}</StoreProvider>
                </ProviderWrapper>
            </body>
        </html>
    );
}
