#!/bin/sh
# . "$(dirname "$0")/_/husky.sh"

# echo '🏗️👷 Styling, testing and building your project before committing'

# Format code with Prettier
# pnpm run format

# npx lint-staged

# Detect code formatting issues
# pnpm run check-format

# Check linting and build
# pnpm run check-lint
# pnpm run check-types
# pnpm run build

#  "dependencies": {
#         "lint-staged": "^13.2.0"
    # },
#   "lint-staged": {
#         "apps/**/*.{js,ts,jsx,tsx}": [
#             "eslint --fix"
#         ],
#         "packages/ui/**/*.{js,ts,jsx,tsx}": [
#             "eslint --fix"
#         ],
#         "*.json": [
#             "prettier --write"
#         ]
#     },
#     "husky": {
#         "hooks": {
#             "pre-commit": "eslint ."
#         }
#     },